const { RichEmbed } = require('discord.js');
const booru = require('booru');
const { field, wordIn } = require('../util');
const config = require('../config');

const noResultsResponse = new RichEmbed({
    fields: [
        field('No results found.', 'Did you [use tags correctly](http://danbooru.donmai.us/wiki_pages/43049)?\n\nKeep in mind we filter out some tags, including "comic".')
    ]
});


const search = async message => {
    if (!wordIn(config.discord.searchChannels, message.channel.id)) {
        return;
    }
    try {
        const tags = (message.cleanContent + config.discord.searchTags).split(' ').splice(1);
        const response = await booru.search('sb', tags, { limit: 1, random: true });
        const image = (await booru.commonfy(response))[0];
        if (!image) {
            return noResultsResponse;
        }
        const sourceWebsite = image.common.source.split('/')[2];
        return new RichEmbed({
            image: {
                url: image.common.file_url
            },
            fields: [
                field('Source', `[${sourceWebsite || image.common.sourceWebsite}](${image.common.source})`),
                field('Tags', image.common.tags.join(' ').replace(/([\_|\*])/g, '\\$1').substr(0, 1023))
            ],
            color: '8700043',
            footer: {
                text: `Generated by ${message.author.username}.`,
                icon_url: message.author.avatarURL
            }
        });
    } catch(err) {
        if (err.name === 'BooruError') {
          //It's a custom error thrown by the package
          if (err.message === '500 Internal Server Error') {
            return 'Could not contact api.';
          } else if (err.message === `You didn't give any images`) {
            return noResultsResponse;
          }
        } else {
          //This means I messed up. Whoops.
          console.error(`Error: ${err}`)
        }
    }
}

module.exports = search;
